export { default as Dashboard } from './Dashboard';
export { default as Login } from './LoginScreen';
export { default as Register } from './Register';
export { default as PatientList } from './PatientList';
export { default as AddPatient } from './AddPatient';
export { default as CreatePrescription } from './CreatePrescription';
export { default as AIPrescription } from './AIPrescription';
export { default as Profile } from './Profile';
export { default as Settings } from './Settings';
